# Generated by Django 5.2.18 on 2026-10-08 10:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('editor', 'Редактор — добавляет, изменяет, удаляет'), ('viewer', 'Наблюдатель — смотрит и комментирует')], default='viewer', max_length=10, verbose_name='роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, editable=False, verbose_name='доступ в /admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('object', 'Объект'), ('group', 'Группа'), ('section', 'Раздел')], default='section', max_length=10, verbose_name='тип')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.folder', verbose_name='внутри')),
            ],
            options={
                'verbose_name': 'папка (объект / группа / раздел)',
                'verbose_name_plural': 'папки (объекты / группы / разделы)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка')], max_length=10, verbose_name='тип')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('url', models.TextField(blank=True, default='', verbose_name='ссылка')),
                ('original_name', models.CharField(blank=True, default='', max_length=500)),
                ('ext', models.CharField(blank=True, default='', max_length=20)),
                ('mime', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('category', models.CharField(default='other', max_length=20)),
                ('storage_name', models.CharField(blank=True, default='', max_length=100)),
                ('preview_name', models.CharField(blank=True, default='', max_length=100)),
                ('preview_mime', models.CharField(blank=True, default='', max_length=100)),
                ('thumb_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='ready', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('content_text', models.TextField(blank=True, default='', editable=False)),
                ('claimed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.folder', verbose_name='папка')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.item')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='folder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='folder_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='item_search_gin'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='item_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'claimed_at'], name='item_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['body'], name='comment_body_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
