# Generated by Django 5.2.18 on 2026-10-08 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_username_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=150, verbose_name='кто')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('upload', 'Загрузил файл'), ('view', 'Открыл'), ('download', 'Скачал'), ('link_create', 'Добавил ссылку'), ('item_edit', 'Изменил документ'), ('item_move', 'Переместил документ'), ('item_delete', 'Удалил документ'), ('folder_create', 'Создал папку'), ('folder_edit', 'Изменил папку'), ('folder_move', 'Переместил папку'), ('folder_delete', 'Удалил папку'), ('comment', 'Прокомментировал'), ('user_create', 'Создал пользователя'), ('user_edit', 'Изменил пользователя'), ('user_delete', 'Удалил пользователя')], max_length=20, verbose_name='действие')),
                ('target', models.CharField(blank=True, default='', max_length=500, verbose_name='объект')),
                ('path', models.CharField(blank=True, default='', max_length=1000, verbose_name='где')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.folder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'журнал действий',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['item', '-id'], name='activity_item_idx'), models.Index(fields=['user', '-id'], name='activity_user_idx'), models.Index(fields=['action', '-id'], name='activity_action_idx')],
            },
        ),
    ]
